- name: Deploy App
  hosts: app
  become: true
  tasks:
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes
        
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith # <-- Указываем нужную ветку
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit

    - name: Show info about the env this host belongs to
      debug:
        msg: "This host is in {{ env }} environment!!!"
      
  handlers: #<-- добавим блок и задачу
  - name: reload puma
    command: systemctl restart puma
   
